### ISSUE TITLE
[suggestion] Handle .fq as well as .fq.gz

### ISSUE THREAD

**Issue by AMChalkie** [datngu/Circall#2]
Hey,

Nice codebase/docker program. 

It would be useful for the code to handle .fq as well as fq.gz.

Best wishes
Alistair

**Comment by datngu** [comment]
Hi Alistair,

Thank you a lot for your interest in Circall and the suggestion.
We will consider adding more input data formats for Circall in the later releases!

Best wishes,
Dat
